# Generated by Django 2.0.6 on 2018-07-04 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180630_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks1', models.CharField(max_length=100)),
                ('marks2', models.CharField(max_length=100)),
                ('marks3', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfile')),
            ],
        ),
    ]
