# Generated by Django 2.0.6 on 2018-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarks',
            name='marks1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks3',
            field=models.IntegerField(),
        ),
    ]
